const Palette = {
  primary: '#0B4F56',
  primaryDark: '#8ADCE2',
  secondary: '#46664E',
  secondaryDark: '#7DA88A',
  accent: '#8A501F',
  accentDark: '#E5A054',
  background: '#F3F0E9',
  backgroundDark: '#121616',
  surface: '#FFFCF6',
  surfaceDark: '#1B2C2C',
  success: '#2E7D32',
  warning: '#874A16',
  error: '#C62828',
  text: '#1C2526',
  textDark: '#F6F2E9',
  border: '#738078',
  borderDark: '#8CA6A0',
} as const;

const light = {
  primary: Palette.primary,
  secondary: Palette.secondary,
  accent: Palette.accent,
  background: Palette.background,
  surface: Palette.surface,
  surfaceRaised: '#FFFEFB',
  surfaceMuted: '#F1F3EF',
  surfaceSelected: '#DDEEE8',
  divider: '#C8D0C8',
  text: Palette.text,
  textPrimary: Palette.text,
  textSecondary: '#405052',
  border: Palette.border,
  focus: '#894500',
  success: Palette.success,
  successSurface: '#E6F3E7',
  warning: Palette.warning,
  warningSurface: '#FFF0DE',
  error: Palette.error,
  errorSurface: '#F9E2E2',
  actionPrimary: Palette.primary,
  onActionPrimary: Palette.surface,
  actionSecondary: '#315D3F',
  onActionSecondary: Palette.surface,
  actionAccent: '#F7D8B7',
  onActionAccent: Palette.text,
  disabled: '#E1E4DF',
  onDisabled: '#5B6667',
  link: Palette.primary,
  icon: Palette.primary,
  tint: Palette.primary,
  tabIconDefault: '#5B6667',
  tabIconSelected: Palette.primary,
} as const;

const dark = {
  primary: Palette.primaryDark,
  secondary: Palette.secondaryDark,
  accent: Palette.accentDark,
  background: Palette.backgroundDark,
  surface: Palette.surfaceDark,
  surfaceRaised: '#263838',
  surfaceMuted: '#203131',
  surfaceSelected: '#294B46',
  divider: '#526A65',
  text: Palette.textDark,
  textPrimary: Palette.textDark,
  textSecondary: '#C5D1CC',
  border: Palette.borderDark,
  focus: Palette.accentDark,
  success: '#81C784',
  successSurface: '#17391F',
  warning: '#FFB45C',
  warningSurface: '#4B2C0D',
  error: '#F2AAAA',
  errorSurface: '#47191D',
  actionPrimary: '#8ADCE2',
  onActionPrimary: Palette.backgroundDark,
  actionSecondary: '#C8E0CE',
  onActionSecondary: Palette.backgroundDark,
  actionAccent: '#F2C894',
  onActionAccent: Palette.backgroundDark,
  disabled: '#344442',
  onDisabled: '#C5D1CC',
  link: '#8ADCE2',
  icon: '#C6D0D0',
  tint: '#8ADCE2',
  tabIconDefault: '#A8B1B1',
  tabIconSelected: '#8ADCE2',
} as const satisfies Record<keyof typeof light, string>;

const highContrast = {
  ...light,
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceRaised: '#FFFFFF',
  surfaceMuted: '#F2F2F2',
  surfaceSelected: '#DCEDE5',
  divider: '#000000',
  text: '#000000',
  textPrimary: '#000000',
  textSecondary: '#202020',
  border: '#000000',
  focus: '#8A3F00',
  actionPrimary: '#003C43',
  actionSecondary: '#174D2A',
  actionAccent: '#FFD59A',
  disabled: '#D6D6D6',
  onDisabled: '#3B3B3B',
  link: '#003C43',
  icon: '#000000',
  tint: '#003C43',
  tabIconDefault: '#202020',
  tabIconSelected: '#003C43',
} as const satisfies Record<keyof typeof light, string>;

export { Palette };
const highContrastDark = {
  ...dark,
  background: '#080C0B', surface: '#101A17', surfaceRaised: '#101A17', surfaceMuted: '#1C2B25',
  surfaceSelected: '#23463D', divider: '#D1E5DB',
  text: '#FFFFFF', textPrimary: '#FFFFFF', textSecondary: '#F0F4F1', border: '#D1E5DB',
  primary: '#B2F4E5', icon: '#FFFFFF', focus: '#FFD59A', link: '#B2F4E5', tint: '#B2F4E5',
  actionPrimary: '#B2F4E5', onActionPrimary: '#080C0B', tabIconSelected: '#B2F4E5', tabIconDefault: '#F0F4F1',
} as const satisfies Record<keyof typeof light, string>;
export const Colors = { light, dark, highContrast, highContrastDark } as const;
export type ThemeColors = (typeof Colors)[keyof typeof Colors];
