const Palette = {
  primary: '#0B4F56',
  primaryDark: '#148A96',
  secondary: '#5B8266',
  secondaryDark: '#7DA88A',
  accent: '#D9822B',
  accentDark: '#E5A054',
  background: '#F9F8F5',
  backgroundDark: '#121616',
  surface: '#FFFFFF',
  surfaceDark: '#1C2222',
  success: '#2E7D32',
  warning: '#ED6C02',
  error: '#C62828',
  text: '#1C2526',
  textDark: '#F0F4F4',
  border: '#D8DCD6',
  borderDark: '#2C3636',
} as const;

const light = {
  primary: Palette.primary,
  secondary: Palette.secondary,
  accent: Palette.accent,
  background: Palette.background,
  surface: Palette.surface,
  surfaceMuted: '#F1F3EF',
  text: Palette.text,
  textSecondary: '#405052',
  border: Palette.border,
  success: Palette.success,
  successSurface: '#E6F3E7',
  warning: Palette.warning,
  warningSurface: '#FFF0DE',
  error: Palette.error,
  actionPrimary: Palette.primary,
  onActionPrimary: Palette.surface,
  actionSecondary: '#315D3F',
  onActionSecondary: Palette.surface,
  actionAccent: '#F7D8B7',
  onActionAccent: Palette.text,
  disabled: '#E1E4DF',
  onDisabled: '#5B6667',
  link: Palette.primary,
  icon: Palette.primary,
  tint: Palette.primary,
  tabIconDefault: '#5B6667',
  tabIconSelected: Palette.primary,
} as const;

const dark = {
  primary: Palette.primaryDark,
  secondary: Palette.secondaryDark,
  accent: Palette.accentDark,
  background: Palette.backgroundDark,
  surface: Palette.surfaceDark,
  surfaceMuted: '#252D2D',
  text: Palette.textDark,
  textSecondary: '#C6D0D0',
  border: Palette.borderDark,
  success: '#81C784',
  successSurface: '#17391F',
  warning: '#FFB45C',
  warningSurface: '#4B2C0D',
  error: '#EF9A9A',
  actionPrimary: '#B9E4E7',
  onActionPrimary: Palette.backgroundDark,
  actionSecondary: '#C8E0CE',
  onActionSecondary: Palette.backgroundDark,
  actionAccent: '#F2C894',
  onActionAccent: Palette.backgroundDark,
  disabled: '#343D3D',
  onDisabled: '#A8B1B1',
  link: '#8ADCE2',
  icon: '#C6D0D0',
  tint: '#8ADCE2',
  tabIconDefault: '#A8B1B1',
  tabIconSelected: '#8ADCE2',
} as const satisfies Record<keyof typeof light, string>;

export { Palette };
export const Colors = { light, dark } as const;
export type ThemeColors = (typeof Colors)[keyof typeof Colors];
