import type { Language } from '../db/schema.types';
const en = {
  gpsTitle:'Find my loved one', gpsPatientTitle:'My location',
  gpsConsent:'Share this device’s location with people you explicitly allow in Family Pairing. Points are kept for up to 24 hours. Location is not sent to AI. You can pause or revoke sharing.',
  gpsForeground:'Updates and safe-zone checks run while Smaran is open on the patient’s device. Background tracking is unavailable in this version. Alerts are shown here; they are not emergency notifications.',
  gpsEnable:'Allow location sharing', gpsPause:'Pause sharing', gpsResume:'Resume sharing', gpsRevoke:'Revoke and erase location',
  gpsCurrent:'Recent location', gpsStale:'Stale location — contact your loved one', gpsUnavailable:'Location unavailable',
  gpsDenied:'Location permission denied. Allow location in device settings.', gpsDisabled:'Device location services are off.',
  gpsOffline:'Offline — waiting to reconnect', gpsPaused:'Location sharing paused',
  gpsSignIn:'Sign in and enable cloud sync for this patient first.', gpsFailed:'Location could not be loaded. Check setup and try again.',
  gpsForbidden:'Location access is unavailable or has been revoked.', gpsConsentRequired:'The patient must first allow location sharing on their device.',
  gpsLoading:'Loading location…', gpsConnected:'Realtime connected', gpsReconnecting:'Realtime reconnecting — checking last known location',
  gpsZone:'Safe zone', gpsRadius:'Radius in metres (100–10,000)', gpsSetZone:'Use latest location as safe-zone centre', gpsClearZone:'Remove safe zone',
  gpsInvalidZone:'Enter a radius between 100 and 10,000 metres.', gpsEntry:'Entered safe zone', gpsExit:'Left safe zone',
  gpsRecenter:'Recenter map', gpsMapUnavailable:'Map unavailable in this build. Location details are shown below.',
  gpsAccuracy:'Accuracy: ±{metres} m', gpsTime:'Recorded: {time}', gpsHistory:'Recent points: {count} (up to 24 hours)',
  gpsSaved:'Location settings saved', gpsPending:'Stopped on this device. Remote pause or revoke will finish when online.',
  gpsNoPair:'Choose a person with location access in Family Pairing.', gpsCoordinates:'Latitude {latitude}, longitude {longitude}',
};
type Catalog = Record<keyof typeof en,string>;
export const locationStrings: Record<Language,Catalog> = {
  en,
  hi:{
    gpsTitle:'अपने प्रियजन को खोजें',gpsPatientTitle:'मेरा स्थान',
    gpsConsent:'इस डिवाइस का स्थान केवल परिवार जोड़ने में चुने गए लोगों से साझा करें। स्थान अधिकतम 24 घंटे रखा जाता है और AI को नहीं भेजा जाता। आप साझा करना रोक या रद्द कर सकते हैं।',
    gpsForeground:'स्थान और सुरक्षित क्षेत्र की जाँच रोगी के डिवाइस पर स्मरण खुला रहने पर होती है। इस संस्करण में पृष्ठभूमि ट्रैकिंग उपलब्ध नहीं है। सूचनाएँ यहाँ दिखती हैं; ये आपातकालीन सूचनाएँ नहीं हैं।',
    gpsEnable:'स्थान साझा करने की अनुमति दें',gpsPause:'साझा करना रोकें',gpsResume:'फिर साझा करें',gpsRevoke:'अनुमति रद्द करें और स्थान मिटाएँ',
    gpsCurrent:'हाल का स्थान',gpsStale:'पुराना स्थान — प्रियजन से संपर्क करें',gpsUnavailable:'स्थान उपलब्ध नहीं',gpsDenied:'स्थान की अनुमति नहीं है। डिवाइस सेटिंग में अनुमति दें।',gpsDisabled:'डिवाइस की स्थान सेवा बंद है।',
    gpsOffline:'ऑफ़लाइन — कनेक्शन की प्रतीक्षा',gpsPaused:'स्थान साझा करना रुका है',gpsSignIn:'पहले साइन इन करें और इस रोगी के लिए क्लाउड सिंक चालू करें।',gpsFailed:'स्थान नहीं खुल सका। सेटअप जाँचकर फिर प्रयास करें।',gpsForbidden:'स्थान की पहुँच उपलब्ध नहीं या रद्द हो गई है।',gpsConsentRequired:'रोगी को पहले अपने डिवाइस पर स्थान साझा करने की अनुमति देनी होगी।',
    gpsLoading:'स्थान लोड हो रहा है…',gpsConnected:'रीयलटाइम जुड़ा है',gpsReconnecting:'रीयलटाइम फिर जुड़ रहा है — अंतिम ज्ञात स्थान जाँचा जा रहा है',gpsZone:'सुरक्षित क्षेत्र',gpsRadius:'दायरा मीटर में (100–10,000)',gpsSetZone:'नवीनतम स्थान को सुरक्षित क्षेत्र का केंद्र बनाएँ',gpsClearZone:'सुरक्षित क्षेत्र हटाएँ',gpsInvalidZone:'100 से 10,000 मीटर का दायरा दर्ज करें।',gpsEntry:'सुरक्षित क्षेत्र में प्रवेश',gpsExit:'सुरक्षित क्षेत्र से बाहर',gpsRecenter:'नक्शे को फिर केंद्रित करें',gpsMapUnavailable:'इस संस्करण में नक्शा उपलब्ध नहीं है। स्थान का विवरण नीचे है।',gpsAccuracy:'सटीकता: ±{metres} मीटर',gpsTime:'दर्ज समय: {time}',gpsHistory:'हाल के स्थान: {count} (अधिकतम 24 घंटे)',gpsSaved:'स्थान सेटिंग सहेजी गई',gpsPending:'इस डिवाइस पर बंद है। ऑनलाइन होने पर दूरस्थ साझाकरण रोकना या रद्द करना पूरा होगा।',gpsNoPair:'परिवार जोड़ने में स्थान की पहुँच वाले व्यक्ति को चुनें।',gpsCoordinates:'अक्षांश {latitude}, देशांतर {longitude}',
  },
  as:{
    gpsTitle:'আপোনজনক বিচাৰক',gpsPatientTitle:'মোৰ অৱস্থান',gpsConsent:'পৰিয়াল সংযোগত আপুনি অনুমতি দিয়া লোকৰ সৈতে এই ডিভাইচৰ অৱস্থান ভাগ কৰক। অৱস্থান সৰ্বাধিক 24 ঘণ্টা ৰখা হয়, AI লৈ পঠোৱা নহয়। আপুনি ভাগ কৰা স্থগিত বা বাতিল কৰিব পাৰে।',gpsForeground:'ৰোগীৰ ডিভাইচত স্মৰণ খোলা থাকিলে অৱস্থান আৰু সুৰক্ষিত এলেকা পৰীক্ষা হয়। এই সংস্কৰণত পটভূমিৰ অনুসৰণ উপলব্ধ নহয়। জাননী ইয়াত দেখুওৱা হয়; এইবোৰ জৰুৰীকালীন জাননী নহয়।',
    gpsEnable:'অৱস্থান ভাগ কৰাৰ অনুমতি দিয়ক',gpsPause:'ভাগ কৰা স্থগিত কৰক',gpsResume:'পুনৰ ভাগ কৰক',gpsRevoke:'অনুমতি বাতিল কৰি অৱস্থান মচক',gpsCurrent:'শেহতীয়া অৱস্থান',gpsStale:'পুৰণি অৱস্থান — আপোনজনৰ সৈতে যোগাযোগ কৰক',gpsUnavailable:'অৱস্থান উপলব্ধ নহয়',gpsDenied:'অৱস্থানৰ অনুমতি নাই। ডিভাইচ ছেটিঙত অনুমতি দিয়ক।',gpsDisabled:'ডিভাইচৰ অৱস্থান সেৱা বন্ধ।',gpsOffline:'অফলাইন — পুনৰ সংযোগৰ অপেক্ষা',gpsPaused:'অৱস্থান ভাগ কৰা স্থগিত',gpsSignIn:'প্ৰথমে ছাইন ইন কৰি এই ৰোগীৰ ক্লাউড ছিংক চালু কৰক।',gpsFailed:'অৱস্থান খুলিব পৰা নগল। ছেটআপ পৰীক্ষা কৰি পুনৰ চেষ্টা কৰক।',gpsForbidden:'অৱস্থানৰ প্ৰৱেশ নাই বা বাতিল হৈছে।',gpsConsentRequired:'ৰোগীয়ে প্ৰথমে নিজৰ ডিভাইচত অৱস্থান ভাগ কৰাৰ অনুমতি দিব লাগিব।',gpsLoading:'অৱস্থান লোড হৈ আছে…',gpsConnected:'ৰিয়েলটাইম সংযুক্ত',gpsReconnecting:'ৰিয়েলটাইম পুনৰ সংযোগ — শেষ জনা অৱস্থান পৰীক্ষা',gpsZone:'সুৰক্ষিত এলেকা',gpsRadius:'মিটাৰত ব্যাসাৰ্ধ (100–10,000)',gpsSetZone:'শেহতীয়া অৱস্থানক সুৰক্ষিত এলেকাৰ কেন্দ্ৰ কৰক',gpsClearZone:'সুৰক্ষিত এলেকা আঁতৰাওক',gpsInvalidZone:'100 ৰ পৰা 10,000 মিটাৰ ব্যাসাৰ্ধ দিয়ক।',gpsEntry:'সুৰক্ষিত এলেকাত প্ৰৱেশ',gpsExit:'সুৰক্ষিত এলেকাৰ বাহিৰত',gpsRecenter:'মানচিত্ৰ পুনৰ কেন্দ্ৰ কৰক',gpsMapUnavailable:'এই সংস্কৰণত মানচিত্ৰ নাই। অৱস্থানৰ বিৱৰণ তলত আছে।',gpsAccuracy:'নিখুঁততা: ±{metres} মিটাৰ',gpsTime:'লিপিবদ্ধ সময়: {time}',gpsHistory:'শেহতীয়া স্থান: {count} (সৰ্বাধিক 24 ঘণ্টা)',gpsSaved:'অৱস্থানৰ ছেটিং সংৰক্ষিত',gpsPending:'এই ডিভাইচত বন্ধ। অনলাইন হলে দূৰৱৰ্তী ভাগ কৰা স্থগিত বা বাতিল সম্পূৰ্ণ হব।',gpsNoPair:'পৰিয়াল সংযোগত অৱস্থানৰ অনুমতি থকা ব্যক্তিক বাছক।',gpsCoordinates:'অক্ষাংশ {latitude}, দ্ৰাঘিমাংশ {longitude}',
  },
  bn:{
    gpsTitle:'প্রিয়জনকে খুঁজুন',gpsPatientTitle:'আমার অবস্থান',gpsConsent:'পরিবার সংযোগে আপনার অনুমতি পাওয়া লোকদের সঙ্গে এই ডিভাইসের অবস্থান ভাগ করুন। অবস্থান সর্বাধিক 24 ঘণ্টা রাখা হয়, AI-তে পাঠানো হয় না। আপনি ভাগ করা থামাতে বা বাতিল করতে পারেন।',gpsForeground:'রোগীর ডিভাইসে স্মরণ খোলা থাকলে অবস্থান ও নিরাপদ এলাকা পরীক্ষা হয়। এই সংস্করণে পটভূমিতে অনুসরণ নেই। বিজ্ঞপ্তি এখানে দেখানো হয়; এগুলি জরুরি বিজ্ঞপ্তি নয়।',gpsEnable:'অবস্থান ভাগ করার অনুমতি দিন',gpsPause:'ভাগ করা থামান',gpsResume:'আবার ভাগ করুন',gpsRevoke:'অনুমতি বাতিল ও অবস্থান মুছুন',gpsCurrent:'সাম্প্রতিক অবস্থান',gpsStale:'পুরোনো অবস্থান — প্রিয়জনের সঙ্গে যোগাযোগ করুন',gpsUnavailable:'অবস্থান পাওয়া যাচ্ছে না',gpsDenied:'অবস্থানের অনুমতি নেই। ডিভাইস সেটিংয়ে অনুমতি দিন।',gpsDisabled:'ডিভাইসের অবস্থান পরিষেবা বন্ধ।',gpsOffline:'অফলাইন — সংযোগের অপেক্ষা',gpsPaused:'অবস্থান ভাগ করা বন্ধ',gpsSignIn:'প্রথমে সাইন ইন করে এই রোগীর ক্লাউড সিঙ্ক চালু করুন।',gpsFailed:'অবস্থান খোলা যায়নি। সেটআপ দেখে আবার চেষ্টা করুন।',gpsForbidden:'অবস্থানের প্রবেশাধিকার নেই বা বাতিল হয়েছে।',gpsConsentRequired:'রোগীকে আগে নিজের ডিভাইসে অবস্থান ভাগ করার অনুমতি দিতে হবে।',gpsLoading:'অবস্থান লোড হচ্ছে…',gpsConnected:'রিয়েলটাইম সংযুক্ত',gpsReconnecting:'রিয়েলটাইম আবার যুক্ত হচ্ছে — শেষ জানা অবস্থান দেখা হচ্ছে',gpsZone:'নিরাপদ এলাকা',gpsRadius:'ব্যাসার্ধ মিটারে (100–10,000)',gpsSetZone:'সর্বশেষ অবস্থানকে নিরাপদ এলাকার কেন্দ্র করুন',gpsClearZone:'নিরাপদ এলাকা সরান',gpsInvalidZone:'100 থেকে 10,000 মিটার ব্যাসার্ধ লিখুন।',gpsEntry:'নিরাপদ এলাকায় প্রবেশ',gpsExit:'নিরাপদ এলাকা ছেড়েছেন',gpsRecenter:'মানচিত্র আবার কেন্দ্রে আনুন',gpsMapUnavailable:'এই সংস্করণে মানচিত্র নেই। অবস্থানের বিবরণ নিচে আছে।',gpsAccuracy:'নির্ভুলতা: ±{metres} মিটার',gpsTime:'রেকর্ডের সময়: {time}',gpsHistory:'সাম্প্রতিক অবস্থান: {count} (সর্বাধিক 24 ঘণ্টা)',gpsSaved:'অবস্থানের সেটিং সংরক্ষিত',gpsPending:'এই ডিভাইসে বন্ধ। অনলাইন হলে দূরবর্তী ভাগ করা থামানো বা বাতিল সম্পূর্ণ হবে।',gpsNoPair:'পরিবার সংযোগে অবস্থানের অনুমতি থাকা ব্যক্তিকে বাছুন।',gpsCoordinates:'অক্ষাংশ {latitude}, দ্রাঘিমাংশ {longitude}',
  },
  mni:{
    gpsTitle:'নুংশিবা মীওই অদুবু থিয়ু',gpsPatientTitle:'ঐগী লৈফম',gpsConsent:'ইমুং মরী শম্নবদা নহাক্না অয়াবা পীরবা মীওইশিংদা ডিভাইস অসিগী লৈফম শেয়র তৌ। লৈফম পুং 24 ফাওবা থম্মি, AI দা থাদে। শেয়র তৌবা লেপ্পা নত্রগা অয়াবা লৌথোকপা য়াই।',gpsForeground:'অনাবগী ডিভাইসতা স্মরণ হাংদুনা লৈরিঙৈদা লৈফম অমসুং সুরক্ষিত মফম য়েংই। ভর্জন অসিদা বেকগ্রাউন্দ ট্রেকিং লৈতে। পাউজেল মফম অসিদা উতলি; অসি জরুরি পাউজেল নত্তে।',gpsEnable:'লৈফম শেয়র তৌবগী অয়াবা পীয়ু',gpsPause:'শেয়র তৌবা লেপ্পু',gpsResume:'অমুক শেয়র তৌ',gpsRevoke:'অয়াবা লৌথোকউ অমসুং লৈফম মুথৎলু',gpsCurrent:'হৌজিক্কী লৈফম',gpsStale:'অরিবা লৈফম — নুংশিবা মীওইদা পাউ ফাউ',gpsUnavailable:'লৈফম ফংদে',gpsDenied:'লৈফমগী অয়াবা লৈতে। ডিভাইস সেটিংদা অয়াবা পীয়ু।',gpsDisabled:'ডিভাইসকী লৈফম সেবা থিংলগনি।',gpsOffline:'ওফলাইন — কানেকশন ঙাইরি',gpsPaused:'লৈফম শেয়র তৌবা লেপ্লে',gpsSignIn:'অহানবদা সাইন ইন তৌদুনা অনাব অসিগী ক্লাউদ সিঙ্ক হাংউ।',gpsFailed:'লৈফম হাংবা ঙমদ্রে। সেটআপ য়েংদুনা অমুক হোৎনবিয়ু।',gpsForbidden:'লৈফম য়েংবগী অয়াবা লৈতে নত্রগা লৌথোকখ্রে।',gpsConsentRequired:'অনাবনা মহাক্কী ডিভাইসতা লৈফম শেয়র তৌবগী অয়াবা অহানবা পীগদবনি।',gpsLoading:'লৈফম লোড তৌরি…',gpsConnected:'রিয়েলটাইম শম্নরে',gpsReconnecting:'রিয়েলটাইম অমুক শম্নরি — অরোইবা খঙবা লৈফম য়েংরি',gpsZone:'সুরক্ষিত মফম',gpsRadius:'মিটরদা রেদিয়স (100–10,000)',gpsSetZone:'অরোইবা লৈফমবু সুরক্ষিত মফমগী ময়াই ওইহল্লু',gpsClearZone:'সুরক্ষিত মফম লৌথোকউ',gpsInvalidZone:'100 দগী 10,000 মিটরগী রেদিয়স ইবিয়ু।',gpsEntry:'সুরক্ষিত মফমদা চঙলে',gpsExit:'সুরক্ষিত মফমদগী থোকখ্রে',gpsRecenter:'মেপ অমুক ময়াইদা থম্মু',gpsMapUnavailable:'ভর্জন অসিদা মেপ ফংদে। লৈফমগী মরোল মখাদা উতলি।',gpsAccuracy:'অচুম্বা: ±{metres} মিটর',gpsTime:'রেকোর্দ তৌবা মতম: {time}',gpsHistory:'অনৌবা লৈফম: {count} (পুং 24 ফাওবা)',gpsSaved:'লৈফমগী সেটিং সেভ তৌরে',gpsPending:'ডিভাইস অসিদা লেপ্লে। ওনলাইন ওইরবদা লাপ্পা শেয়রিং লেপ্পা নত্রগা অয়াবা লৌথোকপা লোইগনি।',gpsNoPair:'ইমুং মরী শম্নবদা লৈফম য়েংবগী অয়াবা লৈবা মীওই খল্লু।',gpsCoordinates:'লেটিট্যুদ {latitude}, লোঞ্জিট্যুদ {longitude}',
  },
  kha:{
    gpsTitle:'Wad ia la kiba ieit',gpsPatientTitle:'Ka jaka jong nga',gpsConsent:'Iasam ia ka jaka jong kane ka kor bad kito ba phi ai jingbit ha ka jingpyniasoh iing. Buhrieh ia ki jaka haduh 24 kynta; ym phah sha AI. Phi lah ban sangeh ne weng jingbit.',gpsForeground:'Ka jaka bad ka jaka shngain ki shah peit katba Smaran ka plie ha ka kor jong u nongpang. Ym don jingbud ha ka background ha kane ka bynta. Ki jingpynbna ki paw hangne; kim dei ki jingpynbna jingma kyrkieh.',gpsEnable:'Ai jingbit ban iasam jaka',gpsPause:'Sangeh iasam shipor',gpsResume:'Iasam biang',gpsRevoke:'Weng jingbit bad pyndam jaka',gpsCurrent:'Ka jaka kaba thymmai',gpsStale:'Ka jaka ka la rim — phone ia la kiba ieit',gpsUnavailable:'Ym lah ban ioh ia ka jaka',gpsDenied:'Ym don jingbit jaka. Ai jingbit ha ki settings jong ka kor.',gpsDisabled:'Ka jingshakri jaka ha ka kor ka la lip.',gpsOffline:'Ym don internet — ap ban pyniasoh biang',gpsPaused:'Ka jingiasam jaka ka la sangeh',gpsSignIn:'Shuwa rung bad plie cloud sync na ka bynta une u nongpang.',gpsFailed:'Ym lah ban plie jaka. Peit ia ka jingpynbeit bad pyrshang biang.',gpsForbidden:'Ym don jingbit peit jaka ne la weng ia ka.',gpsConsentRequired:'U nongpang u dei ban ai jingbit iasam jaka ha la ka kor shuwa.',gpsLoading:'Dang pynrung jaka…',gpsConnected:'Realtime ka la iasoh',gpsReconnecting:'Dang pyniasoh Realtime biang — peit ia ka jaka ba la tip khatduh',gpsZone:'Ka jaka shngain',gpsRadius:'Ka radius ha metre (100–10,000)',gpsSetZone:'Pynlong ia ka jaka thymmai kum ka pdeng jong ka jaka shngain',gpsClearZone:'Weng ia ka jaka shngain',gpsInvalidZone:'Rung ia ka radius hapdeng 100 bad 10,000 metre.',gpsEntry:'La rung ha ka jaka shngain',gpsExit:'La mih na ka jaka shngain',gpsRecenter:'Pynbeit biang ia ka pdeng map',gpsMapUnavailable:'Ym don map ha kane ka bynta. Ki jingtip jaka ki don harum.',gpsAccuracy:'Jingthikna: ±{metres} m',gpsTime:'La buh: {time}',gpsHistory:'Ki jaka thymmai: {count} (haduh 24 kynta)',gpsSaved:'La buh ia ki settings jaka',gpsPending:'La sangeh ha kane ka kor. Ka jingsangeh ne jingweng jingbit na jngai kan dep haba don internet.',gpsNoPair:'Jied ia u briew ba don jingbit jaka ha ka jingpyniasoh iing.',gpsCoordinates:'Latitude {latitude}, longitude {longitude}',
  },
  lus:{
    gpsTitle:'I hmangaihte zawng rawh',gpsPatientTitle:'Ka awmna',gpsConsent:'He phone awmna hi Chhungkaw inzawmnaah i phalna pekte hnenah chauh hrilh rawh. Awmna hi darkar 24 thleng dah a ni a, AI hnenah thawn a ni lo. I chawlhsan emaw phalna i la kir thei.',gpsForeground:'Damdawi enkawl ngai phone-ah Smaran a inhawng lai chauh awmna leh himna hmun enfiah a ni. He version-ah background zuihna a awm lo. Hriattirna he lai ah a lang; chhanchhuahna hriattirna a ni lo.',gpsEnable:'Awmna hrilh phal rawh',gpsPause:'Awmna hrilh chawlhsan rawh',gpsResume:'Awmna hrilh chhunzawm rawh',gpsRevoke:'Phalna la kir la awmna paih rawh',gpsCurrent:'Tuna awmna',gpsStale:'Awmna a hlui tawh — i hmangaih biak rawh',gpsUnavailable:'Awmna hmuh theih a ni lo',gpsDenied:'Awmna phalna a awm lo. Phone settings-ah phalna pe rawh.',gpsDisabled:'Phone awmna service a off.',gpsOffline:'Internet a awm lo — inzawm leh nghah',gpsPaused:'Awmna hrilh chawlhsan a ni',gpsSignIn:'A hmasaah sign in la he mi tan cloud sync hawng rawh.',gpsFailed:'Awmna hawn theih a ni lo. Settings en la han tum leh rawh.',gpsForbidden:'Awmna en phalna a awm lo emaw lak kir a ni tawh.',gpsConsentRequired:'Damdawi enkawl ngai chuan a phone-ah awmna hrilh a phal hmasa tur a ni.',gpsLoading:'Awmna lak mek…',gpsConnected:'Realtime a inzawm',gpsReconnecting:'Realtime inzawm leh mek — awmna hriat hnuhnung en mek',gpsZone:'Himna hmun',gpsRadius:'Radius metre-in (100–10,000)',gpsSetZone:'Awmna hnuhnung ber chu himna hmun laili atan hmang rawh',gpsClearZone:'Himna hmun paih rawh',gpsInvalidZone:'Radius metre 100 leh 10,000 inkar ziak rawh.',gpsEntry:'Himna hmunah a lut',gpsExit:'Himna hmun a chhuahsan',gpsRecenter:'Map laili siam leh rawh',gpsMapUnavailable:'He version-ah map a awm lo. Awmna chanchin a hnuaiah a lang.',gpsAccuracy:'Dikna: ±{metres} m',gpsTime:'Dah hun: {time}',gpsHistory:'Awmna thar: {count} (darkar 24 thleng)',gpsSaved:'Awmna settings dah a ni',gpsPending:'He phone-ah a chawl tawh. Internet a awm hunah hmun dang tana chawlhsan emaw phalna lak kir zawh a ni ang.',gpsNoPair:'Chhungkaw inzawmnaah awmna en phalna nei mi thlang rawh.',gpsCoordinates:'Latitude {latitude}, longitude {longitude}',
  },
};
